version: "3.8"
services:
  joplin:
    build:
      context: .
      args:
        # these variables need to be set in your environment or in a .env file
        NODE_VERSION: ${NODE_VERSION?}
        JOPLIN_VERSION: ${JOPLIN_VERSION?}
    image: jspiers/headless-joplin:${JOPLIN_VERSION?}-node-${NODE_VERSION?}
    volumes:
      - ./joplin-config.json:/secrets/joplin-config.json
      - type: volume
        source: joplin-data
        target: /home/node/.config/joplin
    ports:
      - 3000:80
    command: [joplin, server, start]
volumes:
  joplin-data: {}
