version: "3"
services:
  joplin:
    # build:
    #   context: .
    #   args:
    #     NODE_VERSION: 16.18.0-buster-slim
    #     JOPLIN_VERSION: 2.9.1
    image: jspiers/headless-joplin:2.9.1-node-16.18.0
    volumes:
      - ./joplin-config.json:/secrets/joplin-config.json
      - type: volume
        source: joplin-data
        target: /home/node/.config/joplin
    ports:
      - "3000:80"
    command: ["joplin", "server", "start"]
volumes:
  joplin-data:
