version: "3.8"
services:
  joplin:
    build:
      context: .
      args:
        # these variables need to be set in your environment or in a .env file
        NODE_VERSION: ${NODE_VERSION?}
        JOPLIN_VERSION: ${JOPLIN_VERSION?}
    image: jspiers/headless-joplin:${JOPLIN_VERSION?}-node-${NODE_VERSION?}
    volumes:
      - type: volume
        source: joplin-data
        target: /home/node/.config/joplin
    secrets:
      - joplin-config.json
    env_file:
      # Set JOPLIN_E2EE_MASTER_PASSWORD to non-empty value to enable encryption
      - joplin.env
    ports:
      - 3000:80
    command: [ joplin, server, start ]
volumes:
  joplin-data: {}
secrets:
  joplin-config.json:
    file: ./joplin-config.json
