version: "3.8"
services:
  joplin:
    build:
      context: .
      args:
        # these variables must be provided here or set in a .env file
        NODE_VERSION: ${NODE_VERSION?}
        JOPLIN_VERSION: ${JOPLIN_VERSION?}
    image: jspiers/headless-joplin:${JOPLIN_VERSION?}-node-${NODE_VERSION?}
    volumes:
      - joplin-data:/home/node/.config/joplin
    secrets:
      - joplin-config.json
    ports:
      - "3000:80"
volumes:
  joplin-data: {}
secrets:
  joplin-config.json:
    file: ./joplin-config.json
