version: "3.8"

services:
  joplin:
    build:
      context: .
      args:
        # set these variables in a .env file
        NODE_VERSION: ${NODE_VERSION?}
        JOPLIN_VERSION: ${JOPLIN_VERSION?}
    image: jspiers/headless-joplin:${JOPLIN_VERSION?}-node-${NODE_VERSION?}
