version: "3.8"
services:
  joplin:
    build:
      context: .
      args:
        # these variables need to be hard-coded here or set in a .env file
        NODE_VERSION: ${NODE_VERSION?}
        JOPLIN_VERSION: ${JOPLIN_VERSION?}
    image: jspiers/headless-joplin:${JOPLIN_VERSION?}-node-${NODE_VERSION?}
    volumes:
      - joplin-data:/home/node/.config/joplin
    secrets:
      - joplin-config.json
    environment:
      JOPLIN_SYNC_INTERVAL: 30s
    ports:
      - "3000:80"
volumes:
  joplin-data: {}
secrets:
  joplin-config.json:
    file: ./joplin-config.json
